apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-serve-deployment
  labels:
    app: my-serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-serve
  template:
    metadata:
      labels:
        app: my-serve
    spec:
      containers:
      - name: my-serve
        image: ahmadms1988/cartahub-devops-task
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-serve-service
spec:
  selector:
    app: my-serve
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
