language: python

services:
  - docker

before_install:
  - docker build -t $DOCKER_IMAGE .

script:
  - docker run $DOCKER_IMAGE carta-devops test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ahmadms1988/cartahub-devops-task